config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  get '/pokemon', to: 'pokemon#index', as: 'pokemon_index'
  get '/pokemon/:id', to: 'pokemon#show', as: 'pokemon_show'
  get '/pokemon/:id/checkout', to: 'pokemon#checkout', as: 'pokemon_checkout'
  post '/pokemon/:id/buy', to: 'pokemon#buy', as: 'pokemon_buy'
  post '/pokemon/:id/sell', to: 'pokemon#sell', as: 'pokemon_sell'

  get '/me', to: 'user#index', as: 'user_index'
  get '/me/add', to: 'user#add', as: 'user_add'
  get '/me/transactions', to: 'user#transactions', as: 'user_transactions'
  patch '/me/add', to: 'user#store_money', as: 'user_store_money'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    belongs_to :user
    has_many :transactions
end

app/models/transaction.rb
class Transaction < ApplicationRecord
    belongs_to :user
    belongs_to :pokemon

    OPERATIONS = {
        buy: {
            action: 'BUY'
        },
        sell: {
            action: 'SELL'
        }
    }.freeze
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :pokemons, dependent: :destroy
    has_many :transactions, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    add_flash_types :info, :error, :warning

    def exchange_user
        User.where(
            full_name: "PokéCoin Exchange",
            email: 'pokecoin@example.com',
            password: "whatapass"
        ).first_or_create
    end

    def pokemon_from_logged_user?
        @pokemon.user.id == current_user.id
    end

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:full_name, :email, :password)}
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pokemons = Pokemon.last(8)
  end
end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController
  before_action :authenticate_user!, only: [:checkout, :buy, :sell]
  before_action :fetch_pokemon, only: [:show, :checkout, :sell, :buy]
  before_action :fetch_bitcoin_price, only: [:show, :checkout, :buy, :sell]

  def index
    @pokemons = Pokemon.where(user_id: exchange_user.id).all
  end

  def show; end

  def checkout; end

  def buy
    handle_insufficient_amount if current_user.balance < @price_in_usd

    redirect_to pokemon_show_path if pokemon_from_logged_user?

    handle_transaction(Transaction::OPERATIONS[:buy])

    #do a flash success here later
    redirect_to root_path
  end
  
  def sell
    redirect_to pokemon_show_path unless pokemon_from_logged_user?
    
    handle_transaction(Transaction::OPERATIONS[:sell])

    #do a flash success here later
    redirect_to root_path
  end

  def handle_transaction(operation)
    buyer_id = exchange_user.id

    if Transaction::OPERATIONS[:buy].equal?(operation)
      @price_in_usd = -@price_in_usd
      buyer_id = current_user.id
    end

    User.transaction do
      @user = User.find(current_user.id)
      @user.update(balance: @user.balance + @price_in_usd)
      @pokemon.update(user_id: buyer_id, last_sell_price: @price_in_usd)

      Transaction.new(
        action: operation[:action],
        user_id: current_user.id,
        pokemon_id: @pokemon.id,
        amount: @price_in_usd
      ).save!
    end
  end

  def handle_insufficient_amount
    flash[:error] = "You don't have USD #{@price_in_usd} to buy this."
    redirect_to pokemon_checkout_path
  end

  def fetch_pokemon
    @pokemon = Pokemon.find(params[:id])
  end

  def fetch_bitcoin_price
    @price_in_usd, @btc_price = TickerService.new(pokemon_price: @pokemon.price).call
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
        def to_turbo_stream
            controller.render(options.merge(formats: :html))
        rescue ActionView::MissingTemplate => error
            if get?
                raise error
            elsif has_errors? && default_action
                render rendering_options.merge(formats: :html, status: :unprocessable_entity)
            else
                redirect_to navigation_location
            end
        end
    end

    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!
  before_action :fetch_user

  def index
  end

  def add
  end

  def store_money
    amount = params[:amount].values.first
    @user.update(balance: @user.balance + BigDecimal(amount))

    redirect_to user_index_path
  end

  def transactions
  end

  def fetch_user
    @user = User.find(current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
    def home?
        current_page?('/')
    end
end

app/helpers/pokemon_helper.rb
module PokemonHelper
    def pokemon_from_logged_user?
        return false if current_user.nil?
            
        @pokemon.user.id == current_user.id
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<section class="row align-items-center justify-content-center splash" id="header">
    <div class="col-lg-12 text-center">
        <h1>Trade Pokémons as NFT</h1>
        <%= link_to "Buy new Pokémon now!", pokemon_index_path, class: "btn btn-light btn-lg" %>
    </div>
</section>

<section class="row p-4 pad-card bg-gray" id="description">
    <div class="col text-center">
        <h1 class="mb-4 text-primary">We are the #1 company in this market</h1>

        <div class="container">
            <div class="row g-2">
                <div class="col-lg-4 information-card text-center">
                    <div class="information-inner">
                        <%= image_tag "pokeball.png", class: "img-fluid pokeball" %>
                        <p>We are the first company specialized on the NFT market for Pokémon</p>

                        <a href="#" class="information-cta">Learn more</a>
                    </div>
                </div>

                <div class="col-lg-4 information-card text-center">
                    <div class="information-inner">
                        <%= image_tag "pokeball.png", class: "img-fluid pokeball" %>
                        <p>We are the first company specialized on the NFT market for Pokémon</p>
                        <a href="#" class="information-cta">Learn more</a>
                    </div>
                </div>

                <div class="col-lg-4 information-card text-center">
                    <div class="information-inner">
                        <%= image_tag "pokeball.png", class: "img-fluid pokeball" %>
                        <p>We are the first company specialized on the NFT market for Pokémon</p>

                        <a href="#" class="information-cta">Learn more</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="starttoday" class="row bg-primary text-white p-4 pad-card">
    <div class="col text-center">
        <h1>Start today with only $2 bucks</h1>
        <p>And view your profit increases 100.000x times*</p>
        <small class="text-embromation">* It's actually 1.0001x times</small>
    </div>
</section>

<div class="row bg-gray">
    <section id="pokedex" class="row p-4 justify-content-center pad-card">
        <div class="col text-center">
            <h1 class="mb-4">What Pokémon you want to own today?</h1>
            <p>And we have much more! Sou can see our Portfilio <a href="<%= pokemon_index_path%>">here</a></p>
        </div>
        <%= render "components/pokedex"%>
    </section>

    <section id="staytuned" class="row p-4 justify-content-center">
        <div class="col-6">
            <div class="row justify-content-center">
                <div class="col-12 text-center p-4 cta-card bg-primary text-white">
                    <h1>Stay tuned with us</h1>
                    <p>We'll take all your money =)</p>
                </div>
            </div>
        </div>
    </section>
</div>

<footer class="row bg-danger p-4 text-white pad-card">
    <h1>WARNING: This website is not a real exchange</h1>
    <p>
        Pokecoin is a Ruby On Rails case used on employment tests. We are not connected to any payment service. 
        All operations made here are fictional, in order to just demonstrate the business model.
    </p>
    <p>You can view the source code <a href="https://github.com/leodhb/pokecoin">here</a></p>

    <hr>
    <h1>Home#index</h1>
    <p>Find me in app/views/home/index.html.erb</p>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokecoin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,600;1,700;1,800&display=swap" rel="stylesheet"> 
  </head>

  <body>
    <%= render "components/navbar" %>
    
    <div class="container<%= '-fluid' if home? or current_page?(pokemon_index_url)%>">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pokemon/checkout.html.erb
<h1>Pokemon#checkout</h1>
<p>Find me in app/views/pokemon/checkout.html.erb</p>

<h3><%= @pokemon.name %>'s Checkout</h3>
<img src="<%= @pokemon.image %>" alt="<%= @pokemon.name %>" width="160" height="160">
<p>Base Experience: <%= @pokemon.base_experience %></p>
<p>Height: <%= @pokemon.height %></p>
<p>Weight: <%= @pokemon.weight %></p>
<hr>
<p><%= @pokemon.name %>'s price': <%= @pokemon.price %></p>
<p>Bitcoin Price Today: <%= @btc_price %></p>

<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<% if pokemon_from_logged_user? %>
    <p><%= button_to "Sell for USD #{@price_in_usd.round(2)}", pokemon_sell_path(@pokemon.id) %></p>
<% else %>
    <p><%= button_to "Buy for USD #{@price_in_usd.round(2)}", pokemon_buy_path(@pokemon.id) %></p>
<% end %>

app/views/pokemon/index.html.erb
<section class="row align-items-center justify-content-center p-4 mb-4" id="header">
    <div class="col-lg-12 text-center p-4">
        <h1>Our Pokemon Portfilio</h1>
        <p class="text-white">Grab your own today!!!</p>
    </div>
</section>

<section class="row justify-content-center" id="pokedex-outer">
    <div class="col-lg-7">
        <h3 class="mb-4"><%= @pokemons.count %> pokemon available</h3>
        <%= render "components/pokedex" %>
    </div>
</section>

app/views/pokemon/show.html.erb
<h1>Pokemon#show</h1>
<p>Find me in app/views/pokemon/show.html.erb</p>

<h3><%= @pokemon.name %></h3>
<p>Owner: <%= @pokemon.user.full_name %></p>
<img src="<%= @pokemon.image %>" alt="<%= @pokemon.name %>" width="160" height="160">
<p>Base Experience: <%= @pokemon.base_experience %></p>
<p>Height: <%= @pokemon.height %></p>
<p>Weight: <%= @pokemon.weight %></p>

<% if pokemon_from_logged_user? %>
    <p><%= link_to "Sell for USD #{@price_in_usd}", pokemon_checkout_path(@pokemon.id)%></p>
<% else %>
    <p><%= link_to "Buy for BTC #{@pokemon.price}", pokemon_checkout_path(@pokemon.id)%></p>
<% end %>

app/views/user/add.html.erb
<h1>User#add</h1>
<p>Find me in app/views/user/add.html.erb</p>

<%= form_tag(user_store_money_path, method: "patch") do %>
  <%= label_tag(:amount, "Please tell how much you want to deposit (0 to 10.000 USD):") %>
  <%= number_field(:amount, in: 0..10_000.00, step: 0.5) %>
  <%= submit_tag("Deposit") %>
<% end %>

app/views/user/index.html.erb
<section class="row align-items-center justify-content-center p-4 mb-4" id="header">
    <div class="col-lg-12 text-center p-4">
        <h1>Hello, <%= @user.full_name %></h1>
        <p class="text-white">
            Your current balance is <b>USD <%= @user.balance %></b>.
            <%= link_to "Add +", user_add_path, class: "btn btn-light btn-sm" %>
        </p>
    </div>
</section>

<section class="row" id="userpanel">
    <div class="col-lg-4">
        <h2>Personal data</h2>
        <hr>
        <h4><%= @user.full_name %></h4>
        <p class="text-secondary"><%= @user.email %></p>
        <hr>
        <p><%= @user.pokemons.count %> pokémon and <%= @user.transactions.count %> transactions</p>
        <%= link_to "View transactions", user_transactions_path %>

    </div>

    <div class="col-lg-8">
        <h2>Pokédex</h2>
        <hr>
        <table>
            <tr>
                <th>Name</th>
                <th>Image</th>
                <th>Base XP</th>
                <th>Height</th>
                <th>Weight</th>
                <th>BuyBtn</th>
            </tr>

            <% @user.pokemons.each do |pokemon| %>
                <tr>
                    <td><%= pokemon.name %></td>
                    <td><img src="<%= pokemon.image %>" alt="<%= pokemon.name %>" width="60" height="60"></td>
                    <td><%= pokemon.base_experience %></td>
                    <td><%= pokemon.height %></td>
                    <td><%= pokemon.weight %></td>
                    <td><%= link_to "Sell for #{pokemon.price}", pokemon_show_path(pokemon.id)%></td>
                </tr>
            <% end %>
        </table>
    </div>
</section>

app/views/user/transactions.html.erb
<h1>User#transactions</h1>
<p>Find me in app/views/user/transactions.html.erb</p>

<hr>
<h1><%= @user.full_name %>'s Transactions</h1>
<table>
    <tr>
        <th>Pokemon</th>
        <th>Amount (USD)</th>
        <th>Operation</th>
        <th>Date</th>
    </tr>

    <% @user.transactions.each do |transaction| %>
        <tr>
            <td><%= transaction.pokemon.name %></td>
            <td><%= transaction.amount %></td>
            <td><%= transaction.action %></td>
            <td><%= transaction.created_at.to_s %></td>
        </tr>
    <% end %>
</table>

<%= link_to 'Back', :back %>